[features]
seeds = false
skip-lint = false
[programs.devnet]
upgrade_weapon = "C7KQdF6atRDnJe9cCLomcESLFZCtYa9SEpRT5i9Y4J3u"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "target/deploy/mpl_token_metadata.so" 

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nobody1/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/upgrade_weapon.ts"
